/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.JsonApiBody;
import io.swagger.model.VerifyAccountError;
import io.swagger.model.VerifyAccountResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-04-09T15:21:16.839Z")

@Api(value = "verifyAccountOwner", description = "the verifyAccountOwner API")
public interface VerifyAccountOwnerApi {

    @ApiOperation(value = "Verify Account Owner", nickname = "verifyAccountOwner", notes = "Verify if beneficiary is own of account", response = VerifyAccountResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Beneficiary is account owner", response = VerifyAccountResponse.class),
        @ApiResponse(code = 405, message = "Invalid Input. please put correct request", response = VerifyAccountError.class) })
    @RequestMapping(value = "/verifyAccountOwner",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<VerifyAccountResponse> verifyAccountOwner(@ApiParam(value = "" ,required=true )  @Valid @RequestBody JsonApiBody body);

}
